# Copyright (c) 2022 Dhruva Gole <goledhruva@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# NOTE: This is created to be used for CI/CD workflow. So use it only
# if you are in the zephyrproject directory or else things may break.

manifest:
  self:
    path: modules/lib/ArduinoCore-zephyr

  remotes:
    - name: infineon-github
      url-base: https://github.com/Infineon
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: arduino
      url-base: https://github.com/arduino
    - name: facchinm
      url-base: https://github.com/facchinm
    - name: pillo79
      url-base: https://github.com/pillo79
    - name: lvgl
      url-base: https://github.com/lvgl

  projects:
    - name: zephyr
      remote: infineon-github
      repo-path: ifx-zephyr
      revision: main
      import:
        name-allowlist:
          - cmsis_6
          - mbedtls
          - trusted-firmware-m
          - zcbor

    - name: lvgl
      remote: lvgl
      revision: 92708ebbbb88fed2db15dfe9324f0dc546222301
      path: modules/lib/gui/lvgl

    - name: mtb-ml-middleware
      remote: infineon-github
      repo-path: ml-middleware
      revision: release-v3.2.0
      path: modules/hal/infineon/ml-middleware/mtb-ml-middleware

    - name: mtb-ml-tflite-micro
      remote: infineon-github
      repo-path: ml-tflite-micro
      revision: release-v3.2.0
      path: modules/hal/infineon/ml-tflite-micro/mtb-ml-tflite-micro

    - name: hal_infineon
      remote: infineon-github
      repo-path: ifx-zephyr-hal_infineon
      revision: master
      path: modules/hal/infineon
      groups:
        - hal

    - name: ArduinoCore-API
      path: modules/lib/ArduinoCore-API
      revision: master
      url: https://github.com/arduino/ArduinoCore-API
